### PR TITLE
update REGEX in getUnit fuction to fix cross-browser compatibility

### LINKED ISSUE #3: Lookbehind regex cross-browser support
in the utils.js there is a Lookbehind regex which isn't support it on IE, edge, firefox and safari

its on line 17

```js
return measurement.match(/(?<=[0-9])[^0-9]+$/)[0];
```

https://caniuse.com/#feat=js-regexp-lookbehind

### PR DESCRIPTION
**Pull request by hazem3500**
Fixes #3

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -14,7 +14,7 @@ export const getUnit = measurement => {
     return "px";
   }
 
-  return measurement.match(/(?<=[0-9])[^0-9]+$/)[0];
+  return measurement.match(/^([+-]?(?:\d+|\d*\.\d+))([a-z]*|%)$/)[2];
```
Comment (galacemiguel) [inline src/utils.js]: Can you make the unit part case insensitive?
```suggestion
  return measurement.match(/^([+-]?(?:\d+|\d*\.\d+))([A-Za-z]*|%)$/)[2];
```

**Comment by galacemiguel** [comment]
Awesome, thanks for the initiative! @hazem3500 ✊

**Comment by hazem3500** [comment]
You are welcome ☺️
